### PR TITLE
moved to JSON::MaybeXS

### PR DESCRIPTION
**Pull request by EvanCarroll**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Instead of adding another dep, you could do something like this instead:

    {
        no strict 'refs';
        *::decode_json = eval { require Cpanel::JSON::XS; 1 } ? \&Cpanel::JSON::XS::decode_json : \&JSON::PP::decode_json;
    }

**Comment by EvanCarroll** [comment]
MaybeXS is what *everything* uses. It's not /another/ dep. From Catalyst, to CPAN itself, to the docs for JSON, we're supposed to be using MaybeXS.

**Comment by karenetheridge** [comment]
I'm well aware of the state of the JSON ecosystem. You may not have noticed but I'm the curator of both JSON::Any and JSON::MaybeXS, and wrote most of the documentation you quoted above.

It's another thing that would have to be installed at configure time, which would then pull in other dependencies after that (e.g. Cpanel::JSON::XS), which is why MBT tries to avoid using non-core modules (it only has a few exceptions, and these are very low-level things).

Additionally, it wouldn't even help very much here -- MBT only uses JSON to encode a very small config file, so JSON::PP's relative slowness isn't a concern.

**Comment by EvanCarroll** [comment]
I guess then we just have different estimations of the problem. This forces the install JSON::PP. The solution forces the install of JSON::MaybeXS. Except, JSON::MaybeXS seems more likely to be installed, and will likely result in faster parsing. But, whatever. Didn't realize modules on CPAN were so averse to other reasonable code on CPAN, especially when they're being built with giant abomination like Distzilla.

**Comment by haarg** [comment]
JSON::PP is a core module, and is a hard prerequisite of JSON::MaybeXS.

Saying that JSON::MaybeXS is more likely to be installed makes no sense at all.

**Comment by karenetheridge** [comment]
- JSON::PP is in core. MBT is very high up the toolchain, so it restricts itself to core modules, or other things very high up the toolchain with few or no dependencies.
- if JSON::MaybeXS is not installed, it needs to be before Module::Build::Tiny is installed. This means that Cpanel::JSON::XS, JSON::XS, and all of their dependencies are now prevented from using Module::Build::Tiny to install themselves, and puts themselves higher up the CPAN River than we'd want.

> Didn't realize modules on CPAN were so averse to other reasonable code on CPAN

That's a strawman attack. Things in the toolchain need to be extra-vigilant and mindful of side effects.

**Comment by Leont** [comment]
Module::Build::Tiny is by definition a configure-time dependency, and as such I've tried to keep the number of dependencies low. Not only to keep it light, but also to prevent circular dependencies.

And as @karenetheridge already mentioned while in theory the idea is good, the amount of data I'm reading/writing with these function is so low that using XS is not very sensible. Specially while CPAN::Meta is still using JSON::PP by default.

**Pull request closed without merging**
